package NewDSL.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class DepositWellRow_SubstituteMenu extends SubstituteMenuBase {
  public DepositWellRow_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for DepositWellRow. Generated from implicit smart reference attribute.", new SNodePointer("r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)", "1457717815886264180")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_5ch5ut_a(), CONCEPTS.DepositWellRow$ly));
    result.add(new SMP_Subconcepts_5ch5ut_b());
    return result;
  }

  public class SMP_ReferenceScope_5ch5ut_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_5ch5ut_a() {
      super(CONCEPTS.DepositWellRow$ly, LINKS.depositWell$Yx_L, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_5ch5ut_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_5ch5ut_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "DepositWellRow", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.DepositWellRow$ly);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept DepositWellRow$ly = MetaAdapterFactory.getConcept(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x143adaa156a8b774L, "NewDSL.structure.DepositWellRow");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink depositWell$Yx_L = MetaAdapterFactory.getReferenceLink(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x143adaa156a8b774L, 0x143adaa156bc0781L, "depositWell");
  }
}
