package NewDSL.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.style.AbstractStyleClass;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.editor.runtime.descriptor.EditorBuilderEnvironment;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.nodeEditor.MPSColors;

public class WellSheet_StyleSheet {
  public static class autoindentStyleClass extends AbstractStyleClass {
    public autoindentStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public autoindentStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, true);
    }

  }
  public static class allblueStyleClass extends AbstractStyleClass {
    public allblueStyleClass(EditorContext editorContext, SNode node) {
      super(editorContext, node);
    }
    public allblueStyleClass(EditorBuilderEnvironment builderEnv) {
      super(builderEnv);
    }

    @Override
    public void apply(Style style, EditorCell editorCell) {
      style.set(StyleAttributes.TEXT_COLOR, getStyleRegistry().getSimpleColor(MPSColors.blue));
    }

  }
}
