package NewDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_AlsProductionWell;
  private ConceptPresentation props_CarbonateReservoir;
  private ConceptPresentation props_Coordinates;
  private ConceptPresentation props_DepositWell;
  private ConceptPresentation props_DesignerWell;
  private ConceptPresentation props_ExploratoryWell;
  private ConceptPresentation props_HorizontalWell;
  private ConceptPresentation props_InjectionWell;
  private ConceptPresentation props_InstalledAccessories;
  private ConceptPresentation props_MultilateralWell;
  private ConceptPresentation props_NaturalFlowProductionWell;
  private ConceptPresentation props_ProductionWell;
  private ConceptPresentation props_Reservoir;
  private ConceptPresentation props_SiliciclasticReservoir;
  private ConceptPresentation props_Targets;
  private ConceptPresentation props_Well;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.AlsProductionWell:
        if (props_AlsProductionWell == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_AlsProductionWell = cpb.create();
        }
        return props_AlsProductionWell;
      case LanguageConceptSwitch.CarbonateReservoir:
        if (props_CarbonateReservoir == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_CarbonateReservoir = cpb.create();
        }
        return props_CarbonateReservoir;
      case LanguageConceptSwitch.Coordinates:
        if (props_Coordinates == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Coordinates");
          props_Coordinates = cpb.create();
        }
        return props_Coordinates;
      case LanguageConceptSwitch.DepositWell:
        if (props_DepositWell == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_DepositWell = cpb.create();
        }
        return props_DepositWell;
      case LanguageConceptSwitch.DesignerWell:
        if (props_DesignerWell == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_DesignerWell = cpb.create();
        }
        return props_DesignerWell;
      case LanguageConceptSwitch.ExploratoryWell:
        if (props_ExploratoryWell == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ExploratoryWell = cpb.create();
        }
        return props_ExploratoryWell;
      case LanguageConceptSwitch.HorizontalWell:
        if (props_HorizontalWell == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_HorizontalWell = cpb.create();
        }
        return props_HorizontalWell;
      case LanguageConceptSwitch.InjectionWell:
        if (props_InjectionWell == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_InjectionWell = cpb.create();
        }
        return props_InjectionWell;
      case LanguageConceptSwitch.InstalledAccessories:
        if (props_InstalledAccessories == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("InstalledAccessories");
          props_InstalledAccessories = cpb.create();
        }
        return props_InstalledAccessories;
      case LanguageConceptSwitch.MultilateralWell:
        if (props_MultilateralWell == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_MultilateralWell = cpb.create();
        }
        return props_MultilateralWell;
      case LanguageConceptSwitch.NaturalFlowProductionWell:
        if (props_NaturalFlowProductionWell == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_NaturalFlowProductionWell = cpb.create();
        }
        return props_NaturalFlowProductionWell;
      case LanguageConceptSwitch.ProductionWell:
        if (props_ProductionWell == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_ProductionWell = cpb.create();
        }
        return props_ProductionWell;
      case LanguageConceptSwitch.Reservoir:
        if (props_Reservoir == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_Reservoir = cpb.create();
        }
        return props_Reservoir;
      case LanguageConceptSwitch.SiliciclasticReservoir:
        if (props_SiliciclasticReservoir == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_SiliciclasticReservoir = cpb.create();
        }
        return props_SiliciclasticReservoir;
      case LanguageConceptSwitch.Targets:
        if (props_Targets == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Targets");
          props_Targets = cpb.create();
        }
        return props_Targets;
      case LanguageConceptSwitch.Well:
        if (props_Well == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_Well = cpb.create();
        }
        return props_Well;
    }
    return null;
  }
}
