package NewDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SiliciclasticType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SiliciclasticType() {
    super(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x1dad7a2dd30da9adL, "SiliciclasticType", "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/2138499735303858605");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Shallow_0 = new EnumerationDescriptor.MemberDescriptor("Shallow", "Shallow", 0x1dad7a2dd30da9aeL, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/2138499735303858606");
  private final EnumerationDescriptor.MemberDescriptor myMember_DeepMarine_0 = new EnumerationDescriptor.MemberDescriptor("DeepMarine", "DeepMarine", 0x1dad7a2dd30da9b2L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/2138499735303858610");
  private final EnumerationDescriptor.MemberDescriptor myMember_Lacustrine_0 = new EnumerationDescriptor.MemberDescriptor("Lacustrine", "Lacustrine", 0x1dad7a2dd30da9b6L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/2138499735303858614");
  private final EnumerationDescriptor.MemberDescriptor myMember_Eolian_0 = new EnumerationDescriptor.MemberDescriptor("Eolian", "Eolian", 0x1dad7a2dd30da9bcL, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/2138499735303858620");
  private final EnumerationDescriptor.MemberDescriptor myMember_Fluvial_0 = new EnumerationDescriptor.MemberDescriptor("Fluvial", "Fluvial", 0x1dad7a2dd30da9c2L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/2138499735303858626");
  private final EnumerationDescriptor.MemberDescriptor myMember_Deltaic_0 = new EnumerationDescriptor.MemberDescriptor("Deltaic", "Deltaic", 0x1dad7a2dd30da9caL, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/2138499735303858634");
  private final EnumerationDescriptor.MemberDescriptor myMember_None_0 = new EnumerationDescriptor.MemberDescriptor("None", "None", 0x2a2f59740f81ddf8L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621752");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x1dad7a2dd30da9adL, 0x1dad7a2dd30da9aeL, 0x1dad7a2dd30da9b2L, 0x1dad7a2dd30da9b6L, 0x1dad7a2dd30da9bcL, 0x1dad7a2dd30da9c2L, 0x1dad7a2dd30da9caL, 0x2a2f59740f81ddf8L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Shallow_0, myMember_DeepMarine_0, myMember_Lacustrine_0, myMember_Eolian_0, myMember_Fluvial_0, myMember_Deltaic_0, myMember_None_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_None_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Shallow":
        return myMember_Shallow_0;
      case "DeepMarine":
        return myMember_DeepMarine_0;
      case "Lacustrine":
        return myMember_Lacustrine_0;
      case "Eolian":
        return myMember_Eolian_0;
      case "Fluvial":
        return myMember_Fluvial_0;
      case "Deltaic":
        return myMember_Deltaic_0;
      case "None":
        return myMember_None_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
