package NewDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_DrillingOperation extends EnumerationDescriptorBase {

  public EnumerationDescriptor_DrillingOperation() {
    super(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x2a2f59740f81ddc1L, "DrillingOperation", "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621697");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Offshore_0 = new EnumerationDescriptor.MemberDescriptor("Offshore", "offshore", 0x2a2f59740f81ddc2L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621698");
  private final EnumerationDescriptor.MemberDescriptor myMember_Onshore_0 = new EnumerationDescriptor.MemberDescriptor("Onshore", "onshore", 0x2a2f59740f81ddc4L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621700");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x2a2f59740f81ddc1L, 0x2a2f59740f81ddc2L, 0x2a2f59740f81ddc4L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Offshore_0, myMember_Onshore_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Onshore_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Offshore":
        return myMember_Offshore_0;
      case "Onshore":
        return myMember_Onshore_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
