package NewDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_InjectionType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_InjectionType() {
    super(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x2a2f59740f81de5eL, "InjectionType", "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621854");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Steam_0 = new EnumerationDescriptor.MemberDescriptor("Steam", "Steam", 0x2a2f59740f81de60L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621856");
  private final EnumerationDescriptor.MemberDescriptor myMember_Water_0 = new EnumerationDescriptor.MemberDescriptor("Water", "Water", 0x2a2f59740f81de5fL, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621855");
  private final EnumerationDescriptor.MemberDescriptor myMember_Gas_0 = new EnumerationDescriptor.MemberDescriptor("Gas", "Gas", 0x2a2f59740f81de64L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621860");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x2a2f59740f81de5eL, 0x2a2f59740f81de60L, 0x2a2f59740f81de5fL, 0x2a2f59740f81de64L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Steam_0, myMember_Water_0, myMember_Gas_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Steam":
        return myMember_Steam_0;
      case "Water":
        return myMember_Water_0;
      case "Gas":
        return myMember_Gas_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
