package NewDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_CarbonateType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_CarbonateType() {
    super(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x1dad7a2dd30e511bL, "CarbonateType", "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/2138499735303901467");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Reef_0 = new EnumerationDescriptor.MemberDescriptor("Reef", "Reef", 0x1dad7a2dd30e511cL, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/2138499735303901468");
  private final EnumerationDescriptor.MemberDescriptor myMember_Dolomite_0 = new EnumerationDescriptor.MemberDescriptor("Dolomite", "Dolomite", 0x1dad7a2dd30e511eL, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/2138499735303901470");
  private final EnumerationDescriptor.MemberDescriptor myMember_ClassicLimestone_0 = new EnumerationDescriptor.MemberDescriptor("ClassicLimestone", "ClassicLimestone", 0x1dad7a2dd30e5121L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/2138499735303901473");
  private final EnumerationDescriptor.MemberDescriptor myMember_AfalinicLimestone_0 = new EnumerationDescriptor.MemberDescriptor("AfalinicLimestone", "AfalinicLimestone", 0x1dad7a2dd30e5127L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/2138499735303901479");
  private final EnumerationDescriptor.MemberDescriptor myMember_None_0 = new EnumerationDescriptor.MemberDescriptor("None", "None", 0x2a2f59740f81dde4L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621732");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x1dad7a2dd30e511bL, 0x1dad7a2dd30e511cL, 0x1dad7a2dd30e511eL, 0x1dad7a2dd30e5121L, 0x1dad7a2dd30e5127L, 0x2a2f59740f81dde4L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Reef_0, myMember_Dolomite_0, myMember_ClassicLimestone_0, myMember_AfalinicLimestone_0, myMember_None_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_None_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Reef":
        return myMember_Reef_0;
      case "Dolomite":
        return myMember_Dolomite_0;
      case "ClassicLimestone":
        return myMember_ClassicLimestone_0;
      case "AfalinicLimestone":
        return myMember_AfalinicLimestone_0;
      case "None":
        return myMember_None_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
