package NewDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_WellheadType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_WellheadType() {
    super(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x2a2f59740f81dd84L, "WellheadType", "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621636");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Pumping_0 = new EnumerationDescriptor.MemberDescriptor("Pumping", "pumping", 0x2a2f59740f81dd85L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621637");
  private final EnumerationDescriptor.MemberDescriptor myMember_Flowing_0 = new EnumerationDescriptor.MemberDescriptor("Flowing", "flowing", 0x2a2f59740f81dd86L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621638");
  private final EnumerationDescriptor.MemberDescriptor myMember_Gas_0 = new EnumerationDescriptor.MemberDescriptor("Gas", "gas", 0x2a2f59740f81dd89L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621641");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x2a2f59740f81dd84L, 0x2a2f59740f81dd85L, 0x2a2f59740f81dd86L, 0x2a2f59740f81dd89L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Pumping_0, myMember_Flowing_0, myMember_Gas_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Pumping_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Pumping":
        return myMember_Pumping_0;
      case "Flowing":
        return myMember_Flowing_0;
      case "Gas":
        return myMember_Gas_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
