package NewDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_AlsType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AlsType() {
    super(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x2a2f59740f81de21L, "AlsType", "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621793");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_SuckerRodPump_0 = new EnumerationDescriptor.MemberDescriptor("SuckerRodPump", "SuckerRodPump", 0x2a2f59740f81de22L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621794");
  private final EnumerationDescriptor.MemberDescriptor myMember_ElectricalSubmersiblePump_0 = new EnumerationDescriptor.MemberDescriptor("ElectricalSubmersiblePump", "ElectricalSubmersiblePump", 0x2a2f59740f81de25L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621797");
  private final EnumerationDescriptor.MemberDescriptor myMember_ProgressiveCavityPump_0 = new EnumerationDescriptor.MemberDescriptor("ProgressiveCavityPump", "ProgressiveCavityPump", 0x2a2f59740f81de29L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621801");
  private final EnumerationDescriptor.MemberDescriptor myMember_HydraulicPump_0 = new EnumerationDescriptor.MemberDescriptor("HydraulicPump", "HydraulicPump", 0x2a2f59740f81de2eL, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621806");
  private final EnumerationDescriptor.MemberDescriptor myMember_GasLift_0 = new EnumerationDescriptor.MemberDescriptor("GasLift", "GasLift", 0x2a2f59740f81de35L, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621813");
  private final EnumerationDescriptor.MemberDescriptor myMember_PlungerLift_0 = new EnumerationDescriptor.MemberDescriptor("PlungerLift", "PlungerLift", 0x2a2f59740f81de3cL, "r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/3039746628509621820");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x2a2f59740f81de21L, 0x2a2f59740f81de22L, 0x2a2f59740f81de25L, 0x2a2f59740f81de29L, 0x2a2f59740f81de2eL, 0x2a2f59740f81de35L, 0x2a2f59740f81de3cL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_SuckerRodPump_0, myMember_ElectricalSubmersiblePump_0, myMember_ProgressiveCavityPump_0, myMember_HydraulicPump_0, myMember_GasLift_0, myMember_PlungerLift_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "SuckerRodPump":
        return myMember_SuckerRodPump_0;
      case "ElectricalSubmersiblePump":
        return myMember_ElectricalSubmersiblePump_0;
      case "ProgressiveCavityPump":
        return myMember_ProgressiveCavityPump_0;
      case "HydraulicPump":
        return myMember_HydraulicPump_0;
      case "GasLift":
        return myMember_GasLift_0;
      case "PlungerLift":
        return myMember_PlungerLift_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
