package NewDSL.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AlsProductionWell = 0;
  public static final int AlsType = 1;
  public static final int CarbonateReservoirType = 2;
  public static final int Coordinates = 3;
  public static final int DepositWell = 4;
  public static final int DesignerWell = 5;
  public static final int DrillingOperation = 6;
  public static final int ExploratoryWell = 7;
  public static final int HorizontalWell = 8;
  public static final int InjectionType = 9;
  public static final int InjectionWell = 10;
  public static final int MultilateralWell = 11;
  public static final int ProductionType = 12;
  public static final int ProductionWell = 13;
  public static final int Reservoir = 14;
  public static final int ReservoirType = 15;
  public static final int ReservoriWell = 16;
  public static final int SiliciclasticReservoirType = 17;
  public static final int Well = 18;
  public static final int WellHeadType = 19;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x70d970ca2bc64a80L, 0xa08c12893f37926cL);
    builder.put(0x740a9055b20726afL, AlsProductionWell);
    builder.put(0x740a9055b20726cdL, AlsType);
    builder.put(0x740a9055b206ff92L, CarbonateReservoirType);
    builder.put(0x7b5c7fc646f34c3eL, Coordinates);
    builder.put(0x740a9055b2063623L, DepositWell);
    builder.put(0x2fba2edb99362035L, DesignerWell);
    builder.put(0x3d848a6e7457c41fL, DrillingOperation);
    builder.put(0x7b5c7fc646f34c22L, ExploratoryWell);
    builder.put(0x2fba2edb9936203bL, HorizontalWell);
    builder.put(0x4cde0cd11874358bL, InjectionType);
    builder.put(0x7b5c7fc646f34c31L, InjectionWell);
    builder.put(0x2fba2edb9936202eL, MultilateralWell);
    builder.put(0x4cde0cd11874359dL, ProductionType);
    builder.put(0x7b5c7fc646f34c34L, ProductionWell);
    builder.put(0x740a9055b206ff28L, Reservoir);
    builder.put(0x740a9055b206ff44L, ReservoirType);
    builder.put(0x7b5c7fc646f34c38L, ReservoriWell);
    builder.put(0x740a9055b206ff5aL, SiliciclasticReservoirType);
    builder.put(0x5978c60a757d5133L, Well);
    builder.put(0x3d848a6e74576ef1L, WellHeadType);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
