package NewDSL.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AlsProductionWell = 0;
  public static final int CarbonateReservoir = 1;
  public static final int Coordinates = 2;
  public static final int DepositWell = 3;
  public static final int DesignerWell = 4;
  public static final int ExploratoryWell = 5;
  public static final int HorizontalWell = 6;
  public static final int InjectionWell = 7;
  public static final int InstalledAccessories = 8;
  public static final int MultilateralWell = 9;
  public static final int NaturalFlowProductionWell = 10;
  public static final int ProductionWell = 11;
  public static final int Reservoir = 12;
  public static final int SiliciclasticReservoir = 13;
  public static final int Targets = 14;
  public static final int Well = 15;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x70d970ca2bc64a80L, 0xa08c12893f37926cL);
    builder.put(0x2a2f59740f81de1eL, AlsProductionWell);
    builder.put(0x2a2f59740f81de0bL, CarbonateReservoir);
    builder.put(0x2a2f59740f81dd92L, Coordinates);
    builder.put(0x2a2f59740f81de7dL, DepositWell);
    builder.put(0x2a2f59740f81de94L, DesignerWell);
    builder.put(0x2a2f59740f81de70L, ExploratoryWell);
    builder.put(0x2a2f59740f81de8fL, HorizontalWell);
    builder.put(0x2a2f59740f81de5bL, InjectionWell);
    builder.put(0x2a2f59740f81de50L, InstalledAccessories);
    builder.put(0x2a2f59740f81de9dL, MultilateralWell);
    builder.put(0x2a2f59740f81de1bL, NaturalFlowProductionWell);
    builder.put(0x2a2f59740f81dd6bL, ProductionWell);
    builder.put(0x2a2f59740f81ddcaL, Reservoir);
    builder.put(0x2a2f59740f81de0cL, SiliciclasticReservoir);
    builder.put(0x2a2f59740f81de96L, Targets);
    builder.put(0x2a2f59740f81dd67L, Well);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
