package NewDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptExplorationWell = createDescriptorForExplorationWell();
  /*package*/ final ConceptDescriptor myConceptInjectionWell = createDescriptorForInjectionWell();
  /*package*/ final ConceptDescriptor myConceptLocation = createDescriptorForLocation();
  /*package*/ final ConceptDescriptor myConceptProductionWell = createDescriptorForProductionWell();
  /*package*/ final ConceptDescriptor myConceptReservoriWell = createDescriptorForReservoriWell();
  /*package*/ final ConceptDescriptor myConceptWell = createDescriptorForWell();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptExplorationWell, myConceptInjectionWell, myConceptLocation, myConceptProductionWell, myConceptReservoriWell, myConceptWell);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.ExplorationWell:
        return myConceptExplorationWell;
      case LanguageConceptSwitch.InjectionWell:
        return myConceptInjectionWell;
      case LanguageConceptSwitch.Location:
        return myConceptLocation;
      case LanguageConceptSwitch.ProductionWell:
        return myConceptProductionWell;
      case LanguageConceptSwitch.ReservoriWell:
        return myConceptReservoriWell;
      case LanguageConceptSwitch.Well:
        return myConceptWell;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForExplorationWell() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewDSL", "ExplorationWell", 0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x7b5c7fc646f34c22L);
    b.class_(false, false, true);
    // extends: NewDSL.structure.Well
    b.super_(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x5978c60a757d5133L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/8889120254093118498");
    b.version(3);
    b.aggregate("Location", 0x7b5c7fc646f34c4eL).target(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x7b5c7fc646f34c3eL).optional(false).ordered(true).multiple(false).origin("8889120254093118542").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInjectionWell() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewDSL", "InjectionWell", 0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x7b5c7fc646f34c31L);
    b.class_(false, false, true);
    // extends: NewDSL.structure.Well
    b.super_(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x5978c60a757d5133L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/8889120254093118513");
    b.version(3);
    b.aggregate("location", 0x7b5c7fc646f34c58L).target(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x7b5c7fc646f34c3eL).optional(false).ordered(true).multiple(false).origin("8889120254093118552").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLocation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewDSL", "Location", 0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x7b5c7fc646f34c3eL);
    b.class_(false, true, false);
    b.origin("r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/8889120254093118526");
    b.version(3);
    b.property("latitude", 0x7b5c7fc646f34c43L).type(PrimitiveTypeId.INTEGER).origin("8889120254093118531").done();
    b.property("length", 0x7b5c7fc646f34c45L).type(PrimitiveTypeId.INTEGER).origin("8889120254093118533").done();
    b.property("height", 0x7b5c7fc646f34c49L).type(PrimitiveTypeId.INTEGER).origin("8889120254093118537").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProductionWell() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewDSL", "ProductionWell", 0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x7b5c7fc646f34c34L);
    b.class_(false, false, true);
    // extends: NewDSL.structure.Well
    b.super_(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x5978c60a757d5133L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/8889120254093118516");
    b.version(3);
    b.aggregate("location", 0x7b5c7fc646f34c5aL).target(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x7b5c7fc646f34c3eL).optional(false).ordered(true).multiple(false).origin("8889120254093118554").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReservoriWell() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewDSL", "ReservoriWell", 0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x7b5c7fc646f34c38L);
    b.class_(false, false, true);
    // extends: NewDSL.structure.Well
    b.super_(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x5978c60a757d5133L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/8889120254093118520");
    b.version(3);
    b.aggregate("location", 0x7b5c7fc646f34c5cL).target(0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x7b5c7fc646f34c3eL).optional(false).ordered(true).multiple(false).origin("8889120254093118556").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWell() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewDSL", "Well", 0x70d970ca2bc64a80L, 0xa08c12893f37926cL, 0x5978c60a757d5133L);
    b.class_(false, true, false);
    b.origin("r:c2e19f41-b779-4566-b6a0-4e4349db4a36(NewDSL.structure)/6447120614803984691");
    b.version(3);
    b.property("Name", 0x7b5c7fc646f1786aL).type(PrimitiveTypeId.STRING).origin("8889120254092998762").done();
    return b.create();
  }
}
